Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2021-09, with the labels that each got.

#11 Remove tag automation jobs and scripts
  jobs/aws/eks-anywhere-build-tooling/eks-distro-base-tag-update-periodics.yaml
  jobs/aws/eks-anywhere-prow-jobs/builder-base-tag-update-periodics.yaml
  scripts/pr_automation/builder_base_pr_body
  scripts/pr_automation/update_tag.sh
Labels: approved, lgtm

#13 Bump eksa test ami
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
Labels: approved, lgtm

#14 Add Github issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#16 Remove clone URI and SSH secret from jobs
  jobs/aws/eks-anywhere-build-tooling/bottlerocket-bootstrap-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
  jobs/aws/eks-anywhere-build-tooling/cert-manager-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cilium-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cri-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cli-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cluster-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-bootstrap-provider-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/flux-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/govmomi-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-rbac-proxy-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-vip-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kustomize-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/local-path-provisioner-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/notification-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/vsphere-csi-driver-presubmits.yaml
  jobs/aws/eks-anywhere-prow-jobs/eks-anywhere-prowjobs-lint-presubmits.yaml
  jobs/aws/eks-anywhere/cli-attribution-file-presubmits.yaml
  jobs/aws/eks-anywhere/cli-attribution-files-periodics.yaml
  jobs/aws/eks-anywhere/eks-anywhere-docs-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-cleanup-periodics.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-mocks-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-release-tooling-presubmits.yaml
Labels: approved, lgtm, kind/cleanup

#17 add presubmit for replciatedhq/troubleshoot
  jobs/aws/eks-anywhere-build-tooling/troubleshoot-presubmits.yaml
Labels: approved, lgtm

#18 Add buildkitd sidecar container to attribution periodic, fix run if changed
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-presubmits.yaml
Labels: approved, lgtm

#19 Add name field for build container
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
Labels: approved, lgtm

#20 Point cluster controller presubmit job to CLI repo
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cluster-controller-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
  scripts/lint_prowjobs/main.go
Labels: approved, lgtm, ok-to-test, size/L

#22 Update trigger conditions for cluster controller presubmit
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#24 Only trigger controller presubmit for changes in config or controllers folder at root
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
Labels: approved, lgtm, size/XS

#23 OWNERS file clean up
  OWNERS
Labels: approved, lgtm, size/XS

#27 fix attribution periodic build
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
Labels: approved, lgtm, size/S

#30 Add presubmit for EKS-A diagnostic collector
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
Labels: approved, lgtm, size/M

#31 Bump up go mods to latest stable versions
  go.mod
  go.sum
Labels: approved, lgtm, size/XL
