Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2022-02, with the labels that each got.

#81 Add artifacts bucket env var to PBNJ presubmit
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
Labels: approved, lgtm, size/XS

#82 Adding prow job for tinkerbell/hub project
  jobs/aws/eks-anywhere-build-tooling/hub-presubmit.yaml
Labels: approved, lgtm, size/M

#83 Adding Presubmit job for tinkerbell/hook
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
Labels: approved, lgtm, size/M

#84 Bump buildkit rootless image tag to v0.9.3
  jobs/aws/eks-anywhere-build-tooling/boots-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/bottlerocket-bootstrap-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics-release-0.6.yaml
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
  jobs/aws/eks-anywhere-build-tooling/cert-manager-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cfssl-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-cloudstack-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-tinkerbell-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cli-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-test-image-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-bootstrap-provider-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/flux-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hegel-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/hub-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-rbac-proxy-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-vip-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kustomize-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/local-path-provisioner-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/notification-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/redis-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tink-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/vsphere-csi-driver-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
Labels: approved, lgtm, size/M

#88 Adding local registry side car to prow job
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
Labels: approved, lgtm, size/M

#89 Removing resources on registry container
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
Labels: approved, lgtm, size/XS

#92 Add chrisdoherty4 to owners
  OWNERS
Labels: approved, lgtm, size/XS

#95 run periodic for 07 now
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics-release-0.7.yaml
Labels: approved, lgtm, size/XS

#97 add harbor prow jobs
  jobs/aws/eks-anywhere-build-tooling/distribution-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-helm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
Labels: approved, lgtm, size/L

#101 add more resource to speed up harbor components build
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
Labels: approved, lgtm, size/XS

#100 Check if project path exists before building artifacts
  Makefile
  jobs/aws/eks-anywhere-build-tooling/boots-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/bottlerocket-bootstrap-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cert-manager-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cfssl-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cilium-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloudstack-cloudmonkey-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-cloudstack-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-tinkerbell-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cri-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/distribution-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cli-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-test-image-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-bootstrap-provider-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/flux-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/govmomi-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/grpc-health-probe-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-helm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hegel-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/hub-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-rbac-proxy-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-vip-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kustomize-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/local-path-provisioner-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/notification-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/redis-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tink-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/troubleshoot-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/vsphere-csi-driver-presubmits.yaml
  scripts/lint_prowjobs/main.go
Labels: approved, lgtm, size/L

#99 capas: add presubmit
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-snow-presubmits.yaml
Labels: approved, lgtm, size/M

#102 Remove duplicate envvar field
  jobs/aws/eks-anywhere-build-tooling/bottlerocket-bootstrap-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cli-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tink-presubmits.yaml
Labels: approved, lgtm, size/M

#104 increase disk storage
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
Labels: approved, lgtm, size/XS

#103 use trap for /status/done instead of livenessprobes
  jobs/aws/eks-anywhere-build-tooling/boots-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/bottlerocket-bootstrap-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics-release-0.7.yaml
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics.yaml
  jobs/aws/eks-anywhere-build-tooling/cert-manager-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cfssl-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-aws-snow-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-cloudstack-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-tinkerbell-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-vsphere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-cli-tools-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-test-image-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-bootstrap-provider-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/etcdadm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/flux-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hegel-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/hub-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-rbac-proxy-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kube-vip-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kustomize-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/local-path-provisioner-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/notification-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/redis-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tink-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/vsphere-csi-driver-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
Labels: approved, lgtm, size/XL

#106 Add EKS Anywhere Package presubmit
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-package-image-presubmits.yaml
Labels: approved, lgtm, size/M
