Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2022-06, with the labels that each got.

#155 Remove mrajashree from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#156 Add presubmits for tinkerbell-helm
  jobs/aws/eks-anywhere-build-tooling/tinkerbell-helm-presubmits.yaml
Labels: approved, lgtm, size/M

#157 Remove skip_branches from all the prow jobs
  jobs/aws/eks-anywhere-build-tooling/boots-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cfssl-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-tinkerbell-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-diagnostic-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/grpc-health-probe-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hegel-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/helm-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/hub-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/pbnj-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/rufio-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tink-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/troubleshoot-presubmits.yaml
Labels: approved, lgtm, size/M

#158 Fix tinkerbell-chart project path
  jobs/aws/eks-anywhere-build-tooling/tinkerbell-chart-presubmits.yaml
Labels: approved, lgtm, size/XS

#160 Moving capc from aws to kubernetes-sigs github org
  jobs/aws/eks-anywhere-build-tooling/cluster-api-provider-cloudstack-presubmits.yaml
Labels: approved, lgtm, size/XS

#161 Adds presubmit to validate generated files like staging-build.yml
  jobs/aws/eks-anywhere-build-tooling/validate-generated-presubmit.yaml
Labels: approved, lgtm, size/M

#165 Triggers validate staging build on buildspec change
  jobs/aws/eks-anywhere-build-tooling/validate-generated-presubmit.yaml
Labels: approved, lgtm, size/XS

#166 Fixes validate job trigger
  jobs/aws/eks-anywhere-build-tooling/validate-generated-presubmit.yaml
Labels: approved, lgtm, size/XS

#164 Bump resources for EKS-A CLI presubmit
  jobs/aws/eks-anywhere/eks-anywhere-presubmits.yaml
Labels: approved, lgtm, size/XS

#168 Add attribution periodic for release-0.10 branch
  jobs/aws/eks-anywhere-build-tooling/build-tooling-attribution-files-periodics-release-0.10.yaml
Labels: approved, lgtm

#169 Add metallb presubmit
  jobs/aws/eks-anywhere-build-tooling/metallb-presubmits.yaml
Labels: approved, lgtm, size/M

#172 Max out CPU resources for EKS-A CLI presubmits
  jobs/aws/eks-anywhere/eks-anywhere-presubmits.yaml
Labels: approved, lgtm, size/XS

#173 Update org name for cert-manager project
  jobs/aws/eks-anywhere-build-tooling/cert-manager-cert-manager-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cert-manager-presubmits.yaml
Labels: approved, size/M

#174 Brew update postsubmit job
  jobs/aws/eks-anywhere/eks-anywhere-brew-update-postsubmits.yaml
Labels: approved, lgtm, size/M

#175 Fix branch name
  jobs/aws/eks-anywhere/eks-anywhere-brew-update-postsubmits.yaml
Labels: approved, lgtm, size/XS
