Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2023-11, with the labels that each got.

#338 updating e2e ami
  config/job-constants.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
Labels: approved, lgtm, size/XS

#340 add raymond-zhang00 to owners
  OWNERS
Labels: size/XS

#341 uses build account for metal testing
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-24-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-25-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-26-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-27-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-28-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/imagebuilder-1-X-presubmits.yaml
Labels: approved, lgtm, size/S

#344 updates imagebuilder role arn
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-24-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-25-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-26-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-27-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-28-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/imagebuilder-1-X-presubmits.yaml
Labels: approved, lgtm, size/S

#346 Add a pre-submit for the upgrader image built for in-place upgrades
  jobs/aws/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
Labels: approved, lgtm, size/M

#349 adds presubmits for trigger validations
  jobs/aws/eks-anywhere/eks-anywhere-development-bundle-presubmit.yaml
  jobs/aws/eks-anywhere/eks-anywhere-development-eks-a-release-presubmit.yaml
  jobs/aws/eks-anywhere/eks-anywhere-production-bundle-presubmit.yaml
  jobs/aws/eks-anywhere/eks-anywhere-production-eks-a-release-presubmit.yaml
  scripts/lint_prowjobs/main.go
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-development-bundle-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-development-eks-a-release-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-production-bundle-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-production-eks-a-release-presubmit.yaml
Labels: approved, lgtm, size/L
