Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2024-06, with the labels that each got.

#390 Add tinkerbell chart presubmits
  go.mod
  go.sum
  jobs/aws/eks-anywhere-build-tooling/charts-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/tinkerbell-crds-presubmits.yaml
  scripts/lint_prowjobs/main.go
  templater/jobs/presubmit/eks-anywhere-build-tooling/charts-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/tinkerbell-crds-presubmits.yaml
Labels: approved, lgtm, size/L

#394 Update e2e presubmit jobs to also run in release branches
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-validate-tinkerbell-hardware-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-validate-tinkerbell-hardware-presubmits.yaml
Labels: approved, lgtm, size/XS

#396 Update eks-a e2e test AMI to latest
  config/job-constants.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
Labels: approved, lgtm, size/XS

#391 Deprecate 1-25 branch to remove pre-submits and from the generator
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-25-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-25-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-vsphere-1-25-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-25-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/kind-1-25-presubmits.yaml
  templater/jobs/utils.go
Labels: approved, lgtm, ok-to-test, size/L

#392 Remove jiayiwang7 and taneyland from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#400 Rename charts presubmit to tinkerbell-stack presubmit
  jobs/aws/eks-anywhere-build-tooling/tinkerbell-stack-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/tinkerbell-stack-presubmits.yaml
Labels: approved, lgtm, size/XS
