Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2024-03, with the labels that each got.

#374 Update eks-a e2e test AMI to latest
  config/job-constants.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
Labels: approved, lgtm, size/XS

#376 Remove attribution jobs for release-0.18 branch
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-attribution-periodics-release-0.18.yaml
  templater/jobs/periodic/eks-anywhere-build-tooling/eks-anywhere-attribution-periodics-release-0.18.yaml
Labels: size/L

#377 Skip running EKS-A CLI-related presubmits on release code changes
  jobs/aws/eks-anywhere/eks-anywhere-cli-attribution-presubmit.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-presubmits.yaml
  scripts/lint_prowjobs/main.go
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-cli-attribution-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-presubmits.yaml
  templater/jobs/utils.go
  templater/main.go
Labels: size/S
