Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2024-04, with the labels that each got.

#378 Reserve ephemeral storage for upgrader presubmits
  jobs/aws/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
Labels: approved, lgtm, size/XS

#379 Scope down triggers for E2E presubmit and CLI presubmits further
  jobs/aws/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-cli-attribution-presubmit.yaml
  jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-generate-files-presubmits.yaml
  jobs/aws/eks-anywhere/eks-anywhere-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/eks-a-upgrader-image-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-cli-attribution-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-generate-files-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-presubmits.yaml
Labels: size/S

#382 Add sp1999 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#384 Update E2E amis for presubmits
  config/job-constants.yaml
  jobs/aws/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere/eks-anywhere-e2e-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS
