Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2024-07, with the labels that each got.

#402 only run packges presubmits on main
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-26-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-27-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-28-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-29-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/autoscaler-1-30-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/aws-otel-collector-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/distribution-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/emissary-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/harbor-scanner-trivy-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hello-eks-anywhere-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/metallb-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/metrics-server-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/prometheus-node-exporter-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/prometheus-prometheus-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/redis-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/trivy-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/autoscaler-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/aws-otel-collector-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/distribution-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/emissary-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/harbor-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/harbor-scanner-trivy-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/hello-eks-anywhere-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/metallb-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/metrics-server-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/prometheus-node-exporter-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/prometheus-prometheus-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/redis-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/trivy-presubmits.yaml
Labels: approved, lgtm, size/M

#404 Include kubernetes/cloud-provider-aws presubmit job to run only on main
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-26-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-27-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-28-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-29-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/cloud-provider-aws-1-30-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/cloud-provider-aws-1-X-presubmit.yaml
Labels: approved, lgtm, size/S

#405 fixes hook amd presubmit to use proper env var
  jobs/aws/eks-anywhere-build-tooling/containerd-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  jobs/aws/eks-anywhere-build-tooling/runc-presubmits.yaml
  jobs/aws/eks-anywhere-build-tooling/source-controller-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/containerd-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/hook-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/runc-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/source-controller-presubmits.yaml
Labels: approved, lgtm, size/S

#406 Add presubmits for dhcp project
  go.sum
  jobs/aws/eks-anywhere-build-tooling/dhcp-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/dhcp-presubmits.yaml
Labels: lgtm, size/M
