Repository aws/eks-anywhere-prow-jobs, pull requests merged in 2024-08, with the labels that each got.

#398 Update periodic jobs to point to release-0.20
  jobs/aws/eks-anywhere-build-tooling/eks-anywhere-attribution-periodics-release-0.20.yaml
  templater/jobs/periodic/eks-anywhere-build-tooling/eks-anywhere-attribution-periodics-release-0.20.yaml
Labels: approved, lgtm, size/S

#408 Move PR title condition to run command
  .github/workflows/baseimage-pr-notifier.yml
  .github/workflows/builder-baseimage-pr-notifier.yml
Labels: approved, lgtm, size/S

#410 adds artifacts bucket to hook build
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit-arm64.yaml
  jobs/aws/eks-anywhere-build-tooling/hook-presubmit.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/hook-presubmit-arm64.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/hook-presubmit.yaml
Labels: approved, lgtm, size/XS

#413 Remove base image notifier GitHub workflows
  .github/workflows/baseimage-pr-notifier.yml
  .github/workflows/builder-baseimage-pr-notifier.yml
Labels: approved, lgtm, size/M

#414 adds linuxkit presubmit
  jobs/aws/eks-anywhere-build-tooling/linuxkit-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/linuxkit-presubmits.yaml
Labels: approved, lgtm, size/M

#415 adds more space to linuxkit pre
  jobs/aws/eks-anywhere-build-tooling/linuxkit-presubmits.yaml
  templater/jobs/presubmit/eks-anywhere-build-tooling/linuxkit-presubmits.yaml
Labels: approved, lgtm, size/XS
